"""empty message

Revision ID: 57001e7a2f27
Revises: 91d3870c5adb
Create Date: 2022-11-11 16:53:53.734434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57001e7a2f27'
down_revision = '91d3870c5adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_table')
    # ### end Alembic commands ###
